### ISSUE TITLE
UIFramework cannot be loaded

### ISSUE THREAD

**Issue by Ragnis** [axr/core#107]
`#import UIFramework;` causes an error and a segfault:

```
Error: the file UIFramework.hss doesn't exist build/bin/resources/framework
Segmentation fault
```

This is happening because the app cannot find the resources directory.

**Comment by jakepetroules** [comment]
This does not affect the Cocoa application since its resources are copied into the application bundle. Files simply need to be copied to the correct location with CMake. However there should be no crash if the files are not present (obviously).
