### ISSUE TITLE
Compiling on Debian

### ISSUE THREAD

**Issue by marler8997** [axr/core#108]
After cloning the git repository and running cmake, I am unable to compile using make (running from the src directory).
I've included uname -a to show my OS.

> uname -a
> Linux debian 2.6.32-5-amd64 #1 SMP Sun May 6 04:00:17 UTC 2012 x86_64 GNU/Linux
> 
> make
> [  1%] Building CXX object core/CMakeFiles/AXR_core.dir/AXR.o
> In file included from /home/git/Prototype/src/core/hss/objects/HSSContainer.h:50,
>                  from /home/git/Prototype/src/core/hss/objects/HSSObjects.h:47,
>                  from /home/git/Prototype/src/core/hss/parsing/HSSParser.h:52,
>                  from /home/git/Prototype/src/core/hss/hss.h:52,
>                  from /home/git/Prototype/src/core/AXR.h:162,
>                  from /home/git/Prototype/src/core/AXR.cpp:44:
> /home/git/Prototype/src/core/hss/objects/HSSTextBlock.h:45:30: error: pango/pangocairo.h: No such file or directory
> In file included from /home/git/Prototype/src/core/hss/objects/HSSObjects.h:57,
>                  from /home/git/Prototype/src/core/hss/parsing/HSSParser.h:52,
>                  from /home/git/Prototype/src/core/hss/hss.h:52,
>                  from /home/git/Prototype/src/core/AXR.h:162,
>                  from /home/git/Prototype/src/core/AXR.cpp:44:
> /home/git/Prototype/src/core/hss/objects/HSSPolygon.h:91:59: warning: missing terminating ' character
> /home/git/Prototype/src/core/hss/objects/HSSPolygon.h:91:2: warning: #warning This should probably be an integer... a shape can't have a decimal number of sides
> In file included from /home/git/Prototype/src/core/hss/objects/HSSContainer.h:50,
>                  from /home/git/Prototype/src/core/hss/objects/HSSObjects.h:47,
>                  from /home/git/Prototype/src/core/hss/parsing/HSSParser.h:52,
>                  from /home/git/Prototype/src/core/hss/hss.h:52,
>                  from /home/git/Prototype/src/core/AXR.h:162,
>                  from /home/git/Prototype/src/core/AXR.cpp:44:
> /home/git/Prototype/src/core/hss/objects/HSSTextBlock.h:142: error: ISO C++ forbids declaration of ‘PangoLayout’ with no type
> /home/git/Prototype/src/core/hss/objects/HSSTextBlock.h:142: error: expected ‘;’ before ‘_’ token
> /home/git/Prototype/src/core/hss/objects/HSSTextBlock.h:146: error: ‘PangoWeight’ does not name a type
> make[2]: *_\* [core/CMakeFiles/AXR_core.dir/AXR.o] Error 1
> make[1]: **\* [core/CMakeFiles/AXR_core.dir/all] Error 2
> make: **\* [all] Error 2

**Comment by jakepetroules** [comment]
This was on Debian 6.0.5 (latest version at the time of writing).

**Comment by jakepetroules** [comment]
I believe your issue is that you passed the `src` directory to CMake, whereas you need to pass the repository root directory (i.e. the parent directory of src). CMake works hierarchically and that root file is the one which finds all the include paths and library files necessary to build the project. Try my suggestion and let us know if you're able to compile OK.

**Comment by Mouvedia** [comment]
@jakepetroules you should write all these gotchas on the [wiki page](http://axr.vg/wiki/Building#Linux).

**Comment by jakepetroules** [comment]
Well, his issue is not necessarily Linux-specific, and I wouldn't really call this a "gotcha" as it's more like an "every statement ends with a semicolon" kind of thing. It's a given with any CMake project that you start in the root directory.

**Comment by veosotano** [comment]
Well the big problem here is that the wiki page is outdated, since it hasn't been updated yet to reflect our new build workflow using CMake. We should provide a detailed description of the steps that need to be followed.

**Comment by jakepetroules** [comment]
This has now been done: http://axr.vg/wiki/Building

**Comment by marler8997** [comment]
This morning I cleaned my repository and did the following:

cd /home/git/Prototype
mkdir build
cd build
cmake ..

However, it appears that my two environment variable CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR still have the same value: "/home/git/Prototype".  Based on what I've been reading about cmake, and how the CMakeLists.txt file is checking that these 2 values should be different, it looks like Prototype is expecting CMAKE_BINARY_DIR to be the current working directory?  Is this right or do I need to set it on the command line?

**Comment by matzipan** [comment]
Gonna try this sometime later this evening.

**Comment by jakepetroules** [comment]
This problem was caused by building in the wrong directory and by uncleaned cache files, however I did fix the cause of a couple Debian compile errors in c50f6f2.
