### ISSUE TITLE
text directly inside the xml locks the proto

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#118]
If you don't put text in a tag and then refresh, the proto freezes somehow and can't be refreshed anymore.

**Comment by veosotano** [comment]
It happens with any malformed XML, if I remember correctly. After failing to load, the reload doesn't work anymore, probably because _hasLoadedFile on AXRCore is still true or something like that

**Comment by Ragnis** [comment]
This issue should be renamed then.

**Comment by jakepetroules** [comment]
Should AXRView.mm also be similarly changed? I believe I remember this happening with the Cocoa-based prototype.
