### ISSUE TITLE
implement attr()

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#119]
http://spec.axr.vg/specification.html#1.6.3.2

**Comment by veosotano** [comment]
Moving this to 0.4.9 as it is not really clear how attr() should work in cases where the attribute contains something that is not a number

**Comment by Mouvedia** [comment]
> the attribute contains something that is not a number

AXR/Specification#67

**Comment by Mouvedia** [comment]
```
kwd(attr(thing of selector))
//gives
valueOfThing

attr(thing of selector)
//gives
"valueOfThing"

obj(attr(thing of selector))
//gives
obj(valueOfThing)
```

@veosotano are we good?

**Comment by veosotano** [comment]
As discussed, since the type conversion functions allow to convert any string into the desired type, attr() can always return a string (which, if you think of it, makes a lot of sense: it's just a piece of text in the xml).
