### ISSUE TITLE
Wrapper NPAPI & ActiveX plug-in 

### ISSUE THREAD

**Issue by veosotano** [axr/core#12]
We could use Firebreath: http://www.firebreath.org/display/documentation/FireBreath+Home

Any other ideas? Should we create an individual wrapper for NPAPI and for ActiveX (IE), or should we use a framework like the one above?

**Comment by jakepetroules** [comment]
This is very old and pretty much useless considering the existence of Firebreath, but in case anyone's curious...

https://qt.gitorious.org/qt-solutions/qt-solutions/trees/master/qtbrowserplugin

**Comment by jakepetroules** [comment]
Work on this has begun in d985cdf

**Comment by jakepetroules** [comment]
This issue doesn't belong here anymore due to modularization and because we've already started work on the plugin and gotten it to a somewhat workable state, I'm closing it because it doesn't really describe an actual _issue_.
