### ISSUE TITLE
can't reference font/margin/border

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#125]
```
*
{
    font: @font { color: #808080 }; 
    child
    {
        font: ref(font of @parent); //or @root
    }
}
```

result: child's font is black
expected: should be grey

affected properties: margin, border etc

git version: 634c2ba9fab6b14a492d23937c791be6378771ef

**Comment by veosotano** [comment]
This was fixed by b46e249, 2191487, 6b7387c, 1a3c1c3, cbc6764, ebef41c, bfb313a, 6d7c84d, 2339a45 and 7c4d8e5
