### ISSUE TITLE
Fix filename generation to use full SHA1 hash

### ISSUE THREAD

**Issue by jakepetroules** [axr/core#138]
Currently, package filenames are generated in the format `${version}-git${sha1_short_tag}`. This should be changed to `${version}-git${full_sha1_hash}` to avoid\* the possibility for collisions. This needs to be changed in solar-cmake first, then update the submodule.

*_technically_ reduce, but let's worry about the sun burning out first.

**Comment by jakepetroules** [comment]
After discussion we've decided to simply continue using the sha(7) as the version number itself introduces further entropy and thus should sufficiently mitigate the likelihood of filename collisions. If it is ever a problem then we shall address it.

**Comment by Ragnis** [comment]
By sha(7) you mean 7 first characters of the SHA hash. In case of a collision we could just use more characters from the hash.
