### ISSUE TITLE
Compiler warnings on Linux with GCC 4.6.3.

### ISSUE THREAD

**Issue by aabizri** [axr/core#148]
Warnings with GCC 4.6.3 
Targeting x86_64
On Gentoo Linux
Kernel 3.4.4
https://gist.github.com/a5bd1f0e6462766a8b07

**Comment by jakepetroules** [comment]
We currently have a huge amount of warnings (especially with higher warning levels set). We plan to eliminate the Boost dependency from the core, so the ones you listed should disappear when that happens.

**Comment by jakepetroules** [comment]
This is probably obsolete since we don't use Boost anymore... check and see if you get similar warnings with the new QVariant.

**Comment by aabizri** [comment]
With latest from git and GCC 4.7.2 : https://gist.github.com/7477df1301d5f69ab2fa
_I show great skills at mouse-slipping_

**Comment by jakepetroules** [comment]
Those are completely different warnings... separate issues should be opened as appropriate, otherwise we'll end up using the same issue for what is a completely different problem.

The code that triggered the warnings that this issue originally referred to, is gone.
