### ISSUE TITLE
All target filenames should be standardized according to platform conventions

### ISSUE THREAD

**Issue by Ragnis** [axr/core#156]

**Comment by jakepetroules** [comment]
Can you rename this issue to "all target filenames should be standardized according to platform conventions"? It's not just libCore.so that is a problem...

**Comment by jakepetroules** [comment]
Here are the names we should use:

Target refers to the target name as in `make <target>`, Label refers to the target's label within an IDE, Folder refers to the folder the target will be placed in within an IDE, and Output name refers to the variable part of the filename of the target (i.e. lib{{output-name}}.so, {{output-name}}.dll, {{output-name}}.framework, etc.).

**Target:** core
**Label:** Core
**Folder:** Libraries
**Output name:** axrcore (shared library), AXRCore (framework)

**Target:** qt
**Label:** Qt integration
**Folder:** Libraries
**Output name:** axrqt (shared library) AXRQt (framework)

**Target:** cocoa
**Label:** Cocoa integration
**Folder:** Libraries
**Output name:** axrcocoa (shared library), AXRCocoa (framework)

**Target:** browser
**Label:** Browser
**Output name:** axrbrowser, AXR Browser (bundle)

**Target:** plugin
**Label:** Browser plugin
**Output name:** ???, AXR (bundle)

**Target:** sdl_example
**Label:** SDL example
**Folder:** Examples
**Output name:** sdlexample, SDL Example (bundle)

**Target:** cocoa_example
**Label:** Cocoa example
**Folder:** Examples
**Output name:** cocoaexample, Cocoa Example (bundle)

**Target:** gtk_example
**Label:** GTK example
**Folder:** Examples
**Output name:** gtkexample, GTK Example (bundle)

TODO: Determine the final name of the browser plugin on non OS X systems.

**Comment by jakepetroules** [comment]
This is done. Plugin and example issues need to go in their own respective repositories now.
