### ISSUE TITLE
help > about

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#163]
should have:
1. list of authors
2. link to the website
3. version(s)
4. legal stuff
5. logo

**Comment by jakepetroules** [comment]
Would anyone like to come up with a design for how the items in the dialog should be laid out?

**Comment by aabizri** [comment]
##### I propose either a minimalist about page that have buttons for license and authors, such as new GTK3 apps.

###### About

![Totem's About (using GTK3)](http://i46.tinypic.com/70vxa9.jpg)

###### About:License

![Totem's About:License](http://i46.tinypic.com/2mo8qbk.png)

###### About:Authors

![Totem's About:Authors](http://i48.tinypic.com/2v8o7ic.png)

##### Or a link to load a XML with HSS stylesheet containing about informations , not unlike how firefox does for about:

**Comment by jakepetroules** [comment]
I'd rather not do it in HSS until things are more stable.

**Comment by jakepetroules** [comment]
Can someone propose a few alternate designs so we can have several options to choose from?

**Comment by Mouvedia** [comment]
Migrated to axr/browser#2.
