### ISSUE TITLE
propose to open the last file opened

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#166]

**Comment by jakepetroules** [comment]
This is already implemented - check the preferences dialog.

**Comment by Mouvedia** [comment]
@jakepetroules maybe you didn't understand what I was asking for: currently it opens the last opened file _directly_, which is stupid if it crashed the prototype (you end up not being able to load anything unless you edit the last opened file). So instead it should **ask** if you want to reopen it and maybe even register the fact that it crashed.

**Comment by jakepetroules** [comment]
Good point, I propose to hold the shift or alt/option key when launching the app and it will not automatically open the last file. Thoughts?

**Comment by Ragnis** [comment]
Or maybe the app could detect if it has crashed and not open the file?

**Comment by jakepetroules** [comment]
@Ragnis: Ideas for how we could reliably detect a crash?

**Comment by Ragnis** [comment]
Yes. We could create a file when the app is launched and delete the file
just before the app exits. Now obviously when the app segfaults the file
won't be deleted. So when the app starts the next time we can check if
the file exists and if it does it means that the app has crashed.

**Comment by jakepetroules** [comment]
Sounds good.

**Comment by Mouvedia** [comment]
Migrated to axr/browser#1.
