### ISSUE TITLE
Crash when double clicking

### ISSUE THREAD

**Issue by veosotano** [axr/core#200]
The app crashes because of unhandled exception, probably because the double click event has not been implemented.

BTW, is there a way to control the timing for which a click is single or double (or more) ?

**Comment by jakepetroules** [comment]
Double-click timing is determined by operating system settings. Your guess is correct: https://github.com/axr/core/blob/master/src/core/hss/objects/HSSDisplayObject.cpp#L3861

Unknown event types hit the default case and throw an exception. In our effort to eliminate exceptions (#168) we should probably change that exception to a logging message, and simply let it return false as that indicates that no event was fired.

**Comment by jakepetroules** [comment]
Fixed in 5cca71eb7f + ad8122d0f7
