### ISSUE TITLE
Using @OBJECT.PROPERTY as a value for a property results in a segfault

### ISSUE THREAD

**Issue by Ragnis** [axr/core#208]
Code for reproducing:

```
*
{
    color: #F00;
    background: @this.color;
}
```

**Comment by Mouvedia** [comment]
That's not an issue because dot notation hasn't been implemented yet*. Furthermore #125 is a blocker on this because the instruction is in fact an rgb object.

<sup>*</sup> #39

**Comment by Ragnis** [comment]
It should **not** cause a segfault.

**Comment by Mouvedia** [comment]
That's true. I guess I could put it on the same milestone as #39 since that's when it will become a real problem (till then users won't do that).

**Comment by Mouvedia** [comment]
@veosotano since you have been working on dot notation recently is this still happening?

**Comment by veosotano** [comment]
<del>This is obviously solved</del>

**Comment by veosotano** [comment]
I totally misread the issue, I thought it was about plain dot notation, not in combination with reference objects. My bad. This is still happening atm.
