### ISSUE TITLE
Rename face to faces

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#232]
cf http://hss.axrproject.org/@font#face and http://hss.axrproject.org/@font#faces

**Comment by Mouvedia** [comment]
How will you retrieve the current face?

`ref(face of selector);` will be replaced by…?

**Comment by jakepetroules** [comment]
Based on IRC discussion tonight I believe it is `ref(face[:used] of selector)`

**Comment by Mouvedia** [comment]
So a new type of filter is being introduced for the value selector. I don't think it's warranted but I am not involved anymore so I won't argue further.
