### ISSUE TITLE
@request: can't load files

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#233]
version affected: 0.4.8
code: `on: @click { action: @request { src:"file.xml"; }; };`

I tried using `file:///` without success.

**Comment by veosotano** [comment]
I just tested this code: http://hastebin.com/qobelahuku.xml and it is working fine for me. Is any error appearing in the console? Are you sure file.xml exists?

**Comment by Mouvedia** [comment]
This has been fixed.
