### ISSUE TITLE
Align properties: integers values and anchor properties

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#240]
Currently the anchor properties, when using percentages as values of the align properties, are set to 50% by default. This makes perfect sense. However for integers it's a different story since by convention the expected behaviour is different.
Concretely when you set an align property the corresponding anchor property should be either set to 100% or 0 depending on the current values of the direction and wrapDirection properties.

```
// default

direction: ltr;
wrapDirection: ttb;

// since we are using an integer here and ltr for the direction
alignX: 100;
// the element needs to be pushed on its left side
anchorX: 0;

// similarly this should move the element 100 hss point downward
alignY: 100;
//  hence
anchorY: 0;
```

This issue isn't about the implementation of anchor properties. I am using the properties to illustrate the expected behaviour. Of course you could probably tackle #230 at the same time.

**Comment by veosotano** [comment]
I disagree about this. The value for anchors should remain the same. The fact that elements will have their right edge flush to the align point when at the right side of the parent is a result of "contained", the values of anchor must be predictable and not change all the time.

Also, this should go on the spec repo first.

**Comment by Mouvedia** [comment]
The contained property has not much to do with this defect. If the element is overflowing from its container it has an use, that's it.

This issue is about the default values of anchor properties in relation to the type of value used on align properties. Iv explained the problem in detail. When the user moves an element by 100 hss points he wants it to move by 100 so this doesn't belong on the spec repo. This is not a first: when you use percentage on height/width it relates to the innerheight of the container which is not the case when you use an integer (inner + padding).

If we don't change this now users will have to create complicate reset hss files: this is not desirable and will require an if else construct on the value side. We need to follow the convention.

```
//this should move the element by 100 hss points by default
alignX: 100;
```

**Comment by veosotano** [comment]
It certainly goes into the spec repo: you are complaining about something that is working exactly how it was specced.

On the other hand, this would indeed be the first time that a default value (that of anchorX/Y) changes when you change another property (alignX/Y), which I don't like at all. These kind of changes are not intuitive for the user.

I'm saying we should close this issue.

**Comment by Mouvedia** [comment]
Ill move it on the spec repo as axr/specification#102 but this is critical and follows the expected/conventional behaviour hence why it was opened on the core repo in the first place.
