### ISSUE TITLE
specificity bug with flag functions

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#251]
A

```
    boxy::test {background: #0}
    boxy
    {
    //background: #ccc;
    on: @click { flag(test) };
    }
```

B

```
    boxy::test {background: #0}
    boxy
    {
    background: #ccc;
    on: @click { flag(test) };
    }
```

C

```
    boxy
    {
    background: #ccc;
    on: @click { flag(test) };
    }
    boxy::test {background: #0}
```

In these 3 examples the element's background should change on click. Not currently the case for B because the inner background has a higher specificity: the flag should reset it.

**Comment by veosotano** [comment]
I disagree with this. We don't have such a concept of specificity in HSS. I read example B as:

> `boxy::test {background: #0}`
> If boxy has the flag test, apply the property.

Which then gets overwritten by:

>    boxy
>    {
>        background: #ccc;
>        on: @click { flag(test) };
>    }
> Set the properties on elements called boxy no matter what.

**Comment by Mouvedia** [comment]
The on property **comes after** the inner background property. This on property activates the flag which means the background needs to be changed. What I am missing here?

I could agree with you if the example B looked like this:

```
    boxy::test {background: #0}
    boxy
    {
    on: @click { flag(test) };
    background: #ccc;
    }
```

But even in this case most users would expect the background to be black (during the event).
By not applying the property in the first rule you are implying that boxy with a flag and boxy are equivalent. It's not the case obviously…

**Comment by veosotano** [comment]
This has been settled via IRC chat

**Comment by Mouvedia** [comment]
This is a very serious issue. It can be moved on the spec repo but shouldn't be closed.

**Comment by Mouvedia** [comment]
Migrated to axr/specification#111
