### ISSUE TITLE
Write build instructions

### ISSUE THREAD

**Issue by veosotano** [axr/core#4]

**Comment by veosotano** [comment]
I started to write it. See here: https://github.com/AXR/Prototype/blob/master/INSTALL

It needs to be tested in a clean environment.  @chorfa672m can you try following them and see if it works for you?

**Comment by MChorfa** [comment]
Hey, for sure I will do it for youand give feed back

**Comment by veosotano** [comment]
@chorfa672m please email me your results or post something here. You can also come on IRC, or find me on skype.

**Comment by Mouvedia** [comment]
http://axr.vg/wiki/Building
