### ISSUE TITLE
HTML5 Canvas-based prototype

### ISSUE THREAD

**Issue by matzipan** [axr/core#56]
What would you guys think of this thing? It think it's something that will prove very useful for backward compatibility.

**Comment by Apanatshka** [comment]
Very cool. But a lot of work. I would say it's only doable when we have more people, or when there is a way to develope in one language and have an automatic translation to get it working with canvas objects.

**Comment by matzipan** [comment]
We're still discussing this on the mailing list :P

**Comment by jakepetroules** [comment]
This would require porting our C++ prototype to JavaScript and keeping them in sync - a monumental amount of work which is both unrealistic and would go against our goals. Closing, as agreed upon.
