### ISSUE TITLE
Content jumps down when window size is increased

### ISSUE THREAD

**Issue by shviller** [axr/core#85]
In this document
https://dl.dropbox.com/u/762468/AXR/bugs/window_width_increase.zip
The contents of the `<note>` elements (green rounded rectangles) moves down when the window's width is increased, with the increment being bigger than some undetermined value (that is, changing the window's size just a bit won't display the issue). This doesn't happen when the window width is decreased, either.

**Comment by jakepetroules** [comment]
Was this on the Cocoa or SDL application? No repro on Cocoa and could not test on SDL.

**Comment by shviller** [comment]
SDL, on Windows.

**Comment by jakepetroules** [comment]
Moved to axr/examples#5
