### ISSUE TITLE
Reproducible crash with malformed selector

### ISSUE THREAD

**Issue by jakepetroules** [axr/core#91]
The malformed selector shown in the following paste crashes the prototype. The crash is reproducible 100% of the time. Paste includes offending files and full stack trace.

http://pastebin.com/vu5VsJhy

**Comment by Mouvedia** [comment]
reduction:

```
* @a { }
```

**Comment by Ragnis** [comment]
Patch: http://hastebin.com/raw/hadufiqotu

**Comment by jakepetroules** [comment]
I'm getting a 404 on that link. Also @Ragnis, can you please submit any patches as pull requests? I think it'll be a lot easier to keep track of them that way.

Plus then you get credit for the bugfix. ;)

**Comment by Ragnis** [comment]
Looks like they have deleted that link.

BTW if you properly apply the patch, the commit will be still under my name.
