### ISSUE TITLE
content property: sel() as value

### ISSUE THREAD

**Issue by Mouvedia** [axr/core#97]
sel() function needs to be added as a valid value.

**Comment by veosotano** [comment]
What would this do? Don't you mean ref() ?

**Comment by Mouvedia** [comment]
@veosotano it's used to _dynamically mirror the content_ of another element.
It needs to return one element (or elements having exactly the same content). It would be easier (for you) to just error out when there's more than one element returned by the selector.

**Comment by Mouvedia** [comment]
Already covered by `ref()`.
